# Feature Engineering Basics

In [2]:
import pandas as pd
import numpy as np


df=pd.read_csv('https://raw.githubusercontent.com/subhadipml/Mercedes-Benz-Greener-Manufacturing/master/train.csv',usecols=['X1','X2'])
df.head()

X1  X2
0  v  at
1  t  av
2  w   n
3  t   n
4  v   n

In [3]:
for col in df.columns:
    print(col,":",len(df[col].unique()),"labels")

X1 : 27 labels
X2 : 44 labels


In [13]:
df.X2.value_counts().to_dict()

{'as': 1659,
 'ae': 496,
 'ai': 415,
 'm': 367,
 'ak': 265,
 'r': 153,
 'n': 137,
 's': 94,
 'f': 87,
 'e': 81,
 'aq': 63,
 'ay': 54,
 'a': 47,
 't': 29,
 'k': 25,
 'i': 25,
 'b': 21,
 'ao': 20,
 'z': 19,
 'ag': 19,
 'd': 18,
 'ac': 13,
 'g': 12,
 'ap': 11,
 'y': 11,
 'x': 10,
 'aw': 8,
 'h': 6,
 'at': 6,
 'an': 5,
 'al': 5,
 'q': 5,
 'av': 4,
 'ah': 4,
 'p': 4,
 'au': 3,
 'j': 1,
 'c': 1,
 'am': 1,
 'af': 1,
 'l': 1,
 'o': 1,
 'aa': 1,
 'ar': 1}

In [14]:
df_freq=df.X2.value_counts().to_dict()

df.X2=df.X2.map(df_freq)

In [15]:
df.head()

X1   X2
0  v    6
1  t    4
2  w  137
3  t  137
4  v  137

## Ordinal Encoder Transform

In [29]:
from sklearn.preprocessing import OrdinalEncoder

data=np.asarray(['red','green','blue']).reshape(-1, 1)
data

array([['red'],
       ['green'],
       ['blue']], dtype='<U5')

In [28]:
encoder=OrdinalEncoder()
res=encoder.fit_transform(data)
res

array([[2.],
       [1.],
       [0.]])

In [31]:
from sklearn.preprocessing import LabelEncoder

label_encoder=LabelEncoder()
res=label_encoder.fit_transform(['red','blue','green'])
res

array([2, 0, 1], dtype=int64)

## Diffrence Between Label_Encoder and Ordinal_Encoder


OrdinalEncoder for 2D data; shape (n_samples, n_features), LabelEncoder is for 1D data: for shape (n_samples,)

LabelEncoder learns ->classes_

OrdinalEncoder learns ->categories_


#LabelEncoder().fit(['a','b']).classes_
>>> array(['a', 'b'], dtype='<U1')

OrdinalEncoder().fit([['a'], ['b']]).categories_
 >>> [array(['a', 'b'], dtype=object)]

# One Hot Encoder

In [39]:
from sklearn.preprocessing import OneHotEncoder

one_hot=OneHotEncoder(drop='first',sparse=False)
res=one_hot.fit_transform(data)
res

array([[0., 1.],
       [1., 0.],
       [0., 0.]])

#Breast Cancer Dataset

In [43]:
dataset=pd.read_csv('https://raw.githubusercontent.com/jbrownlee/Datasets/master/breast-cancer.csv',header=None)
dataset.head()

0          1        2      3      4    5        6           7      8  \
0  '40-49'  'premeno'  '15-19'  '0-2'  'yes'  '3'  'right'   'left_up'   'no'   
1  '50-59'     'ge40'  '15-19'  '0-2'   'no'  '1'  'right'   'central'   'no'   
2  '50-59'     'ge40'  '35-39'  '0-2'   'no'  '2'   'left'  'left_low'   'no'   
3  '40-49'  'premeno'  '35-39'  '0-2'  'yes'  '3'  'right'  'left_low'  'yes'   
4  '40-49'  'premeno'  '30-34'  '3-5'  'yes'  '2'   'left'  'right_up'   'no'   

                        9  
0     'recurrence-events'  
1  'no-recurrence-events'  
2     'recurrence-events'  
3  'no-recurrence-events'  
4     'recurrence-events'

In [47]:
data=dataset.values
data.shape

(286, 10)

In [53]:
X=data[:,:-1].astype(str)
Y=data[:,-1].astype(str)

In [54]:
type(X)

numpy.ndarray

In [56]:
one_hot=OneHotEncoder(drop='first',sparse=False)
res=one_hot.fit_transform(X)
res

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 1., 0., 0.]])

In [59]:
encoder=OrdinalEncoder()
res=encoder.fit_transform(X)
res

array([[2., 2., 2., ..., 1., 2., 0.],
       [3., 0., 2., ..., 1., 0., 0.],
       [3., 0., 6., ..., 0., 1., 0.],
       ...,
       [1., 2., 5., ..., 1., 4., 0.],
       [3., 2., 2., ..., 1., 1., 0.],
       [3., 0., 7., ..., 0., 4., 0.]])

In [62]:
encoder=LabelEncoder()
res=encoder.fit_transform(Y)
res

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

# Handling Categorical data
https://towardsdatascience.com/understanding-feature-engineering-part-1-continuous-numeric-data-da4e47099a7b

Transforming NOMINAL DATA

In [35]:
dataset=pd.read_csv('https://raw.githubusercontent.com/dipanjanS/practical-machine-learning-with-python/master/notebooks/Ch04_Feature_Engineering_and_Selection/datasets/vgsales.csv',usecols=['Name','Platform','Year','Genre','Publisher'])
dataset.head()

Name Platform    Year         Genre Publisher
0                Wii Sports      Wii  2006.0        Sports  Nintendo
1         Super Mario Bros.      NES  1985.0      Platform  Nintendo
2            Mario Kart Wii      Wii  2008.0        Racing  Nintendo
3         Wii Sports Resort      Wii  2009.0        Sports  Nintendo
4  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo

In [36]:
for cols in dataset.columns:
    print(cols,":",len(dataset[cols].unique()))

Name : 11493
Platform : 31
Year : 40
Genre : 12
Publisher : 579


In [37]:
dataset['Genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

Lets create th Label Encoding for Genre

In [38]:
from sklearn.preprocessing import LabelEncoder

gen_label_encoder=LabelEncoder()
gen_labels=gen_label_encoder.fit_transform(dataset['Genre'])
genre_mapping={index:label for index,label in enumerate(gen_label_encoder.classes_)}
genre_mapping

{0: 'Action',
 1: 'Adventure',
 2: 'Fighting',
 3: 'Misc',
 4: 'Platform',
 5: 'Puzzle',
 6: 'Racing',
 7: 'Role-Playing',
 8: 'Shooter',
 9: 'Simulation',
 10: 'Sports',
 11: 'Strategy'}

Thus a mapping scheme has been generated where each genre value is mapped to a number with the help of the LabelEncoder object gle. The transformed labels are stored in the genre_labels value which we can write back to our data frame.

In [39]:
dataset['Genre_Label']=gen_labels
dataset.head()

Name Platform    Year         Genre Publisher  \
0                Wii Sports      Wii  2006.0        Sports  Nintendo   
1         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   Genre_Label  
0           10  
1            4  
2            6  
3           10  
4            7

These labels can be used directly often especially with frameworks like scikit-learn if you plan to use them as response variables for prediction, however as discussed earlier, we will need an additional step of encoding on these before we can use them as features.

Transforming Ordinal Category

In [40]:
p_dataset=pd.read_csv('https://raw.githubusercontent.com/dipanjanS/practical-machine-learning-with-python/master/notebooks/Ch04_Feature_Engineering_and_Selection/datasets/Pokemon.csv')
p_dataset=p_dataset.sample(random_state=1, 
                         frac=1).reset_index(drop=True)
p_dataset.head()

#                       Name  Type 1  Type 2  Total  HP  Attack  Defense  \
0    6  CharizardMega Charizard Y    Fire  Flying    634  78     104       78   
1  460                  Abomasnow   Grass     Ice    494  90      92       75   
2  161                    Sentret  Normal     NaN    215  35      46       34   
3  667                     Litleo    Fire  Normal    369  62      50       58   
4  224                  Octillery   Water     NaN    480  75     105       75   

   Sp. Atk  Sp. Def  Speed Generation  Legendary  
0      159      115    100      Gen 1      False  
1       92       85     60      Gen 4      False  
2       35       45     20      Gen 2      False  
3       73       54     72      Gen 6      False  
4      105       75     45      Gen 2      False

In [41]:
for cols in p_dataset.columns:
    print(cols,":",len(p_dataset[cols].unique()))

# : 721
Name : 800
Type 1 : 18
Type 2 : 19
Total : 200
HP : 94
Attack : 111
Defense : 103
Sp. Atk : 105
Sp. Def : 92
Speed : 108
Generation : 6
Legendary : 2


In [42]:
p_dataset['Generation'].unique()

array(['Gen 1', 'Gen 4', 'Gen 2', 'Gen 6', 'Gen 3', 'Gen 5'], dtype=object)

Based on the above output, we can see there are a total of 6 generations and each Pokémon typically belongs to a specific generation based on the video games (when they were released) and also the television series follows a similar timeline. This attribute is typically ordinal (domain knowledge is necessary here) because most Pokémon belonging to Generation 1 were introduced earlier in the video games and the television shows than Generation 2 as so on. 

In [43]:
gen_ord_map = {'Gen 1': 1, 'Gen 2': 2, 'Gen 3': 3, 
               'Gen 4': 4, 'Gen 5': 5, 'Gen 6': 6}
p_dataset['GenerationLabel'] = p_dataset['Generation'].map(gen_ord_map)

In [44]:
p_dataset.head()

#                       Name  Type 1  Type 2  Total  HP  Attack  Defense  \
0    6  CharizardMega Charizard Y    Fire  Flying    634  78     104       78   
1  460                  Abomasnow   Grass     Ice    494  90      92       75   
2  161                    Sentret  Normal     NaN    215  35      46       34   
3  667                     Litleo    Fire  Normal    369  62      50       58   
4  224                  Octillery   Water     NaN    480  75     105       75   

   Sp. Atk  Sp. Def  Speed Generation  Legendary  GenerationLabel  
0      159      115    100      Gen 1      False                1  
1       92       85     60      Gen 4      False                4  
2       35       45     20      Gen 2      False                2  
3       73       54     72      Gen 6      False                6  
4      105       75     45      Gen 2      False                2

One Hot Encoding

Considering we have the numeric representation of any categorical attribute with m labels (after transformation), the one-hot encoding scheme, encodes or transforms the attribute into m binary features which can only contain a value of 1 or 0. Each observation in the categorical feature is thus converted into a vector of size m with only one of the values as 1 (indicating it as active).

In [45]:
p_dataset[['Name', 'Generation', 'Legendary']].head()

Name Generation  Legendary
0  CharizardMega Charizard Y      Gen 1      False
1                  Abomasnow      Gen 4      False
2                    Sentret      Gen 2      False
3                     Litleo      Gen 6      False
4                  Octillery      Gen 2      False

The attributes of interest are Pokémon Generation and their Legendary status. The first step is to transform these attributes into numeric representations

In [46]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

gle=LabelEncoder()
gen_labels=gle.fit_transform(p_dataset['Generation'])
p_dataset['Gen_Labels']=gen_labels

lle=LabelEncoder()
len_labels=lle.fit_transform(p_dataset['Legendary'])
p_dataset['Len_Labels']=len_labels

In [47]:
p_dataset.head()

#                       Name  Type 1  Type 2  Total  HP  Attack  Defense  \
0    6  CharizardMega Charizard Y    Fire  Flying    634  78     104       78   
1  460                  Abomasnow   Grass     Ice    494  90      92       75   
2  161                    Sentret  Normal     NaN    215  35      46       34   
3  667                     Litleo    Fire  Normal    369  62      50       58   
4  224                  Octillery   Water     NaN    480  75     105       75   

   Sp. Atk  Sp. Def  Speed Generation  Legendary  GenerationLabel  Gen_Labels  \
0      159      115    100      Gen 1      False                1           0   
1       92       85     60      Gen 4      False                4           3   
2       35       45     20      Gen 2      False                2           1   
3       73       54     72      Gen 6      False                6           5   
4      105       75     45      Gen 2      False                2           1   

   Len_Labels  
0           0  
1           0  
2           0  
3           0  
4           0

In [52]:
p_df=p_dataset[['Name', 'Generation', 'Gen_Labels',  
                       'Legendary', 'Len_Labels']]

p_df.head()

Name Generation  Gen_Labels  Legendary  Len_Labels
0  CharizardMega Charizard Y      Gen 1           0      False           0
1                  Abomasnow      Gen 4           3      False           0
2                    Sentret      Gen 2           1      False           0
3                     Litleo      Gen 6           5      False           0
4                  Octillery      Gen 2           1      False           0

The features Gen_Labels and Lgnd_Labels now depict the numeric representations of our categorical features. Let’s now apply the one-hot encoding scheme on these features.

In [69]:
gen_ohe=OneHotEncoder()
gen_feature_array=gen_ohe.fit_transform(p_df[['Gen_Labels']]).toarray()
gen_feature_labels=list(gle.classes_)
gen_feature=pd.DataFrame(gen_feature_array,columns=gen_feature_labels)


len_ohe=OneHotEncoder()
len_feature_array=len_ohe.fit_transform(p_df[['Len_Labels']]).toarray()
len_feature_labels=list(lle.classes_)
len_feature=pd.DataFrame(len_feature_array,columns=len_feature_labels)



C:\Users\Dishaa\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Dishaa\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you 

In [67]:
gen_feature.head()

Gen 1  Gen 2  Gen 3  Gen 4  Gen 5  Gen 6
0    1.0    0.0    0.0    0.0    0.0    0.0
1    0.0    0.0    0.0    1.0    0.0    0.0
2    0.0    1.0    0.0    0.0    0.0    0.0
3    0.0    0.0    0.0    0.0    0.0    1.0
4    0.0    1.0    0.0    0.0    0.0    0.0

In [70]:
len_feature.head()

False  True 
0    1.0    0.0
1    1.0    0.0
2    1.0    0.0
3    1.0    0.0
4    1.0    0.0

In [76]:
p_dataset_ohe=pd.concat([p_df,gen_feature,len_feature],axis=1)
p_dataset_ohe.head()

Name Generation  Gen_Labels  Legendary  Len_Labels  \
0  CharizardMega Charizard Y      Gen 1           0      False           0   
1                  Abomasnow      Gen 4           3      False           0   
2                    Sentret      Gen 2           1      False           0   
3                     Litleo      Gen 6           5      False           0   
4                  Octillery      Gen 2           1      False           0   

   Gen 1  Gen 2  Gen 3  Gen 4  Gen 5  Gen 6  False  True  
0    1.0    0.0    0.0    0.0    0.0    0.0    1.0   0.0  
1    0.0    0.0    0.0    1.0    0.0    0.0    1.0   0.0  
2    0.0    1.0    0.0    0.0    0.0    0.0    1.0   0.0  
3    0.0    0.0    0.0    0.0    0.0    1.0    1.0   0.0  
4    0.0    1.0    0.0    0.0    0.0    0.0    1.0   0.0

Thus you can see that 6 dummy variables or binary features have been created for Generation and 2 for Legendary since those are the total number of distinct categories in each of these attributes respectively. Active state of a category is indicated by the 1 value in one of these dummy variables which is quite evident from the above data frame.

Consider you built this encoding scheme on your training data and built some model and now you have some new data which has to be engineered for features before predictions as follows.

In [77]:
new_poke_df = pd.DataFrame([['PikaZoom', 'Gen 3', True], 
                           ['CharMyToast', 'Gen 4', False]],
                       columns=['Name', 'Generation', 'Legendary'])
new_poke_df

Name Generation  Legendary
0     PikaZoom      Gen 3       True
1  CharMyToast      Gen 4      False

You can leverage scikit-learn’s excellent API here by calling the transform(…) function of the previously build LabeLEncoder and OneHotEncoder objects on the new data. Remember the workflow, first we do the transformation.


"transform" uses a previously computed mean and std to autoscale the data (subtract mean from all values and then divide it by std). "fit_transform" does both at the same time.

In [78]:
new_gen_labels=gle.transform(new_poke_df['Generation'])
new_poke_df['Gen_Labels']=new_gen_labels

new_len_labels=lle.transform(new_poke_df['Legendary'])
new_poke_df['Len_Labels']=new_len_labels

In [79]:
new_poke_df.head()

Name Generation  Legendary  Gen_Labels  Len_Labels
0     PikaZoom      Gen 3       True           2           1
1  CharMyToast      Gen 4      False           3           0

Once we have numerical labels, let’s apply the encoding scheme now!

In [80]:
new_gen_feature_array=gen_ohe.transform(new_poke_df[['Gen_Labels']]).toarray()
new_gen_feature=pd.DataFrame(new_gen_feature_array,columns=gen_feature_labels)


new_len_feature_array=len_ohe.transform(new_poke_df[['Len_Labels']]).toarray()
new_len_feature=pd.DataFrame(new_len_feature_array,columns=len_feature_labels)


In [81]:
new_poke_ohe=pd.concat([new_poke_df,new_gen_feature,new_len_feature],axis=1)

In [82]:
new_poke_ohe.head()

Name Generation  Legendary  Gen_Labels  Len_Labels  Gen 1  Gen 2  \
0     PikaZoom      Gen 3       True           2           1    0.0    0.0   
1  CharMyToast      Gen 4      False           3           0    0.0    0.0   

   Gen 3  Gen 4  Gen 5  Gen 6  False  True  
0    1.0    0.0    0.0    0.0    0.0   1.0  
1    0.0    1.0    0.0    0.0    1.0   0.0